model = "gpt-5.1-codex-max"
model_reasoning_effort = "medium"
approval_policy = "never"
sandbox_mode = "danger-full-access"

[projects."/Users/thesofakillers/repos/interview_prep"]
trust_level = "trusted"

[projects."/Users/thesofakillers/workspace"]
trust_level = "trusted"

[projects."/Users/thesofakillers/repos/flywheel"]
trust_level = "trusted"

[notice]
hide_full_access_warning = true
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[features]
web_search_request = true
